name: "Install"
description: "Sets up Node.js and runs install"

runs:
  using: composite
  steps:
    # pnpm for our dependencies
    - uses: pnpm/action-setup@v3
      with:
        version: 9
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        check-latest: true
        registry-url: "https://registry.npmjs.org"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install
