name: Unit Test

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch:

# env:

jobs:
  test:
    name: Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup & Install
        uses: ./.github/composite-actions/install

      - name: Run Unit Tests
        run: pnpm test
        env:
          NODE_ENV: "test"
